import {
  LocationData,
  WorkspaceTypeData,
  FranchiseModelData,
  FranchiseTermData,
  MediaVideoData,
  BlogPostData,
  TestimonialData,
  FAQData,
  SiteSettings,
} from '@/types';

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  companyName: 'Yoffices',
  tagline: 'Premium Managed Workspaces, Co-living & Commercial Franchise Ecosystem',
  phone: '+91 99990 00000',
  whatsappNumber: '919999000000',
  whatsappDefaultMsg: 'Hi Yoffices team, I would like to inquire about workspaces / franchise opportunities in Gurgaon.',
  email: 'contact@yoffices.com',
  corporateAddress: 'Institutional Area, Sector 32, Gurugram, Haryana 122001',
  operationalAddress: 'Plot No. 863, Near Huda City Metro, Sector 45, Gurugram, Haryana 122003',
  officeHours: 'Monday – Sunday: 8:00 AM – 9:00 PM (24/7 Access for Cabin & Resident Members)',
  disclaimerText: 'Terms shown are based on information supplied by Yoffices and are subject to the final executed agreement and current approved terms.',
  bannerEnabled: true,
  bannerText: '✨ Discover Flagship Managed Workspaces & Co-living in Sector 45 Gurgaon. Book a Guided Center Walk-through today!',
  bannerLink: '/book-a-visit',
  socialLinks: {
    linkedin: 'https://linkedin.com/company/yoffices',
    instagram: 'https://instagram.com/yoffices',
    youtube: 'https://youtube.com/@yoffices',
    facebook: 'https://facebook.com/yoffices',
  },
};

export const INITIAL_LOCATIONS: LocationData[] = [
  {
    id: 'loc-sec-45',
    slug: 'gurgaon-sector-45',
    name: 'Sector 45 Executive Center',
    city: 'Gurugram',
    area: 'Sector 45 (Near Huda City Centre / Millennium City Metro)',
    workspaceAddress: 'Plot No. 863, Sector 45, Gurugram, Haryana 122003',
    corporateAddress: 'Institutional Area, Sector 32, Gurugram, Haryana 122001',
    photos: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
    ],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14032.74712061214!2d77.0601!3d28.4439!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d18f0a0d4c1b9%3A0x7d01309f3e4e9b8!2sSector%2045%2C%20Gurugram%2C%20Haryana!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
    googleMapsUrl: 'https://maps.google.com/?q=Sector+45+Gurugram+Haryana',
    workspaceTypes: ['private-office', 'workstations', 'coworking', 'meeting-rooms', 'work-stay'],
    amenities: [
      'High-Speed Redundant 1Gbps Fiber Internet',
      'Ergonomic Herman Miller Style Acoustic Workstations',
      '24/7 Biometric Smart Card Access',
      'Soundproof Executive Boardrooms with 4K AV Displays',
      'Continuous 100% DG Power Backup & UPS',
      'Artisan Coffee & Gourmet Tea Pantry',
      'Secure On-Site Two & Four-Wheeler Parking',
      'Integrated Work + Stay Co-living Suites',
    ],
    status: 'Operational',
    published: true,
    order: 1,
  },
  {
    id: 'loc-sec-32',
    slug: 'gurgaon-sector-32-institutional',
    name: 'Sector 32 Corporate Desk & Compliance Office',
    city: 'Gurugram',
    area: 'Sector 32 Institutional Area (NH-48 Corridor)',
    workspaceAddress: 'Institutional Area, Sector 32, Gurugram, Haryana 122001',
    corporateAddress: 'Institutional Area, Sector 32, Gurugram, Haryana 122001',
    photos: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
    ],
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14030.123456789!2d77.0421!3d28.4556!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d1901a1b2c3d4%3A0x5e6f7a8b9c0d1e2f!2sSector%2032%2C%20Gurugram%2C%20Haryana!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
    googleMapsUrl: 'https://maps.google.com/?q=Sector+32+Gurugram+Haryana',
    workspaceTypes: ['virtual-office', 'meeting-rooms', 'private-office'],
    amenities: [
      'Corporate Headquarters Reception & Concierge',
      'Haryana GST & ROC Regulatory Compliance Filing',
      'Secure Mail & Courier Management Dispatch',
      'VIP Boardroom for Investor & Client Presentations',
      'Direct Expressway Connectivity to Delhi & IGI Airport',
    ],
    status: 'Operational',
    published: true,
    order: 2,
  },
];

export const INITIAL_WORKSPACES: WorkspaceTypeData[] = [
  {
    id: 'ws-private-office',
    slug: 'private-office',
    name: 'Private Offices & Lockable Cabins',
    shortDesc: 'Acoustically treated, fully furnished private cabins for teams of 2 to 50 members.',
    fullDesc: 'Experience absolute privacy and enterprise security in our dedicated private offices. Each cabin comes equipped with custom branded signage, soundproofing, high-speed dedicated LAN connections, executive ergonomic seating, and customizable layouts suited to your team’s culture.',
    startingPrice: '₹8,500',
    priceUnit: 'seat / month',
    idealFor: 'Growing Startups, Tech Teams, Consulting Firms, and Enterprise Satellite Offices',
    features: [
      'Private Keycard / Biometric Lockable Access',
      'Complimentary Conference & Boardroom Credits',
      'Dedicated High-Speed Bandwidth & Firewall Setup',
      'Daily Professional Housekeeping & Sanitization',
      'Inclusive of Electricity, Air Conditioning & High-Speed Internet',
    ],
    heroImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    ],
    published: true,
    order: 1,
  },
  {
    id: 'ws-workstations',
    slug: 'workstations',
    name: 'Dedicated Workstations & Fixed Desks',
    shortDesc: 'Reserved, dedicated desks with personal lockable storage in vibrant collaborative zones.',
    fullDesc: 'Your own fixed desk in our premium collaborative open floors. Never worry about finding a seat again. Keep your monitors, files, and personal equipment locked safely in your under-desk pedestal.',
    startingPrice: '₹5,500',
    priceUnit: 'desk / month',
    idealFor: 'Freelancers, Solo Founders, Remote Engineers, and Boutique Agencies',
    features: [
      'Assigned Fixed Desk with Ergonomic Mesh Chair',
      'Personal Under-Desk Lockable Storage Unit',
      'Multi-Port Power & High-Speed LAN Ports at Every Desk',
      'Unlimited High-Speed Wi-Fi & Beverage Access',
      'Community Networking & Industry Masterclass Access',
    ],
    heroImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
    ],
    published: true,
    order: 2,
  },
  {
    id: 'ws-coworking',
    slug: 'coworking',
    name: 'Flexible Coworking & Hot Desks',
    shortDesc: 'Agile hot desking plans and flexible day passes for mobile professionals.',
    fullDesc: 'Drop in, plug in, and get straight to work. Access versatile open lounge seating, high-speed Wi-Fi, premium coffee, and quiet breakout phone booths whenever you need focused work hours in Gurgaon.',
    startingPrice: '₹4,500',
    priceUnit: 'month (or ₹499/day)',
    idealFor: 'Digital Nomads, Hybrid Workers, Consultants, and Traveling Executives',
    features: [
      'Flexible Hot Desk Seating Across Open Lounges',
      'High-Speed Enterprise Wi-Fi with Zero Downtime',
      'Acoustic Calling Booths for Private Phone Calls',
      'Pantry Access with Free Artisan Tea & Coffee',
      'Flexible Daily, 10-Day, and Monthly Flex Passes',
    ],
    heroImage: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=1200&q=80',
    ],
    published: true,
    order: 3,
  },
  {
    id: 'ws-meeting-rooms',
    slug: 'meeting-rooms',
    name: 'Conference & Executive Boardrooms',
    shortDesc: 'State-of-the-art meeting rooms with 4K projection, VC setup, and whiteboards.',
    fullDesc: 'Host impactful client presentations, investor pitches, board reviews, and hybrid video conferences in our sound-isolated meeting rooms. Available on hourly, half-day, or full-day bookings with concierge beverage service.',
    startingPrice: '₹600',
    priceUnit: 'hour',
    idealFor: 'Client Pitches, Board Meetings, Interviews, and Hybrid Video Calls',
    features: [
      'Ultra-HD 4K Displays with Wireless Screen Mirroring',
      'High-Fidelity Polycom / Logitech VC Conferencing Hardware',
      'Magnetic Glass Whiteboards & Presentation Kits',
      'Acoustic Wall Paneling for Maximum Speech Privacy',
      'In-Room Concierge Coffee, Tea & Water Service',
    ],
    heroImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
    ],
    published: true,
    order: 4,
  },
];

export const INITIAL_FRANCHISE_MODELS: FranchiseModelData[] = [
  {
    id: 'model-desk',
    slug: 'desk-workstation-model',
    name: 'Workstation / Desk Asset Model',
    shortDesc: 'Entry-level fractional workspace asset allocation with monthly commercial rental returns.',
    description: 'Designed for individual professionals and retail HNIs seeking steady monthly commercial rental cash flow backed by prime Gurgaon office infrastructure.',
    principal: 500000,
    monthlyRental: 5000,
    annualRental: 60000,
    threeYearRental: 180000,
    statedTotal: 680000,
    termYears: 3,
    chequesCount: 3,
    disbursementFrequency: 'Monthly Direct Bank Transfer',
    highlights: [
      'Principal Amount: ₹5,00,000',
      'Monthly Rental Disbursement: ₹5,000 / month',
      'Annual Rental Payout: ₹60,000 / year',
      '3-Year Cumulative Rental: ₹1,80,000',
      'Stated Total Realization: ₹6,80,000 (after 3 Years)',
      'Security: 3 Post-Dated Annual Security Cheques',
    ],
    idealFor: 'HNIs, First-time Commercial Asset Partners, and Salaried Executives',
    published: true,
    order: 1,
  },
  {
    id: 'model-dormitory',
    slug: 'dormitory-work-stay-model',
    name: 'Dormitory / Work + Stay Co-living Model',
    shortDesc: 'Dual-yield hospitality & co-living asset combining dedicated workspace with managed living.',
    description: 'Capitalize on Gurgaon’s immense workforce influx requiring turnkey Work + Stay accommodations near Cyber City and metro hubs.',
    principal: 1100000,
    monthlyRental: 11000,
    annualRental: 132000,
    threeYearRental: 396000,
    statedTotal: 1496000,
    termYears: 3,
    chequesCount: 3,
    disbursementFrequency: 'Monthly Direct Bank Transfer',
    highlights: [
      'Principal Amount: ₹11,00,000',
      'Monthly Rental Disbursement: ₹11,000 / month',
      'Annual Rental Payout: ₹1,32,000 / year',
      '3-Year Cumulative Rental: ₹3,96,000',
      'Stated Total Realization: ₹14,96,000 (after 3 Years)',
      'High-occupancy residential + workstation synergy',
      'Security: 3 Post-Dated Annual Security Cheques',
    ],
    idealFor: 'Co-living asset builders, institutional allocators, and real estate partners',
    published: true,
    order: 2,
  },
  {
    id: 'model-cabin',
    slug: 'cabin-executive-suite-model',
    name: 'Executive Cabin (8 Seater / 3+1) Model',
    shortDesc: 'Flagship commercial private office unit commanding premium enterprise tenancy yields.',
    description: 'High-ticket private office suite leased to funded startups and multinational corporate branches in Gurgaon.',
    principal: 2500000,
    monthlyRental: 25000,
    annualRental: 300000,
    threeYearRental: 900000,
    statedTotal: 3400000,
    termYears: 3,
    chequesCount: 3,
    disbursementFrequency: 'Monthly Direct Bank Transfer',
    highlights: [
      'Principal Amount: ₹25,00,000',
      'Monthly Rental Disbursement: ₹25,000 / month',
      'Annual Rental Payout: ₹3,00,000 / year',
      '3-Year Cumulative Rental: ₹9,00,000',
      'Stated Total Realization: ₹34,00,000 (after 3 Years)',
      'Enterprise grade private suite allocation',
      'Security: 3 Post-Dated Annual Security Cheques',
    ],
    idealFor: 'Family Offices, Ultra-HNIs, and Commercial Real Estate Portfolios',
    published: true,
    order: 3,
  },
];

export const INITIAL_FRANCHISE_TERMS: FranchiseTermData[] = [
  {
    id: 'term-tenure',
    title: '3-Year Agreement Validity',
    description: 'All franchise models operate under a structured 3-year term agreement with fixed monthly rental covenants.',
    category: 'Tenure',
    order: 1,
  },
  {
    id: 'term-cheques',
    title: '3 Post-Dated Annual Security Cheques',
    description: 'Yoffices issues 3 post-dated annual security cheques to the partner upfront upon execution of the formal bilateral agreement.',
    category: 'Security',
    order: 2,
  },
  {
    id: 'term-return',
    title: 'Annual Cheque Return Protocol',
    description: 'At the end of each operational year, upon successful completion of monthly rental disbursements, the partner returns that specific year’s security cheque.',
    category: 'Workflow',
    order: 3,
  },
  {
    id: 'term-maturity',
    title: 'Year 3 Principal Settlement / Renewal',
    description: 'At the conclusion of Year 3, the final principal is settled or the agreement is mutually renewed under revised commercial terms.',
    category: 'Settlement',
    order: 4,
  },
];

export const INITIAL_MEDIA_VIDEOS: MediaVideoData[] = [
  {
    id: 'vid-sec45-walkthrough',
    title: 'Inside Yoffices Sector 45 Gurugram: Flagship Workspace & Cabin Walkthrough',
    slug: 'inside-yoffices-sector-45-gurugram-walkthrough',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    description: 'Explore the high-speed fiber corridors, acoustic private cabins, conference rooms, and gourmet cafeteria at our premier Sector 45 Gurgaon center.',
    category: 'Office Tours',
    isFeatured: true,
    publishedAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 'vid-franchise-breakdown',
    title: 'Commercial Real Estate Passive Income: Understanding the 3 Yoffices Franchise Models',
    slug: 'commercial-real-estate-passive-income-franchise-models',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    description: 'A comprehensive financial breakdown of the Desk (₹5L), Dormitory (₹11L), and Cabin (₹25L) franchise structures with security cheque mechanics.',
    category: 'Rental Income',
    isFeatured: true,
    publishedAt: '2026-07-28T14:30:00Z',
  },
  {
    id: 'vid-gst-virtual-office',
    title: 'Haryana GST & MCA Company Registration via Virtual Office: Step-by-Step Guide',
    slug: 'haryana-gst-mca-virtual-office-guide',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    description: 'How to obtain verified Rent Agreements, Electricity Bills, and NOCs for rapid GST registration at Sector 32 & Sector 45 Gurugram.',
    category: 'Virtual Office',
    isFeatured: false,
    publishedAt: '2026-08-05T09:00:00Z',
  },
];

export const INITIAL_BLOG_POSTS: BlogPostData[] = [
  {
    id: 'blog-gurgaon-coworking-2026',
    title: 'Why Gurgaon Enterprises are Moving from Traditional Leases to Managed Private Cabins',
    slug: 'gurgaon-enterprises-managed-private-cabins-vs-traditional-leases',
    excerpt: 'Traditional 9-year commercial lock-ins are obsolete. Discover why high-growth companies in Gurgaon prefer agile, fully serviced managed offices.',
    content: `Commercial real estate dynamics in Gurugram have fundamentally shifted in 2026. Enterprise leaders, startup founders, and expanding MNCs are moving away from capital-intensive 9-year raw commercial leases toward agile, turnkey managed workspace ecosystems.

### 1. Zero Upfront Capital Expenditure (CapEx)
Building out a conventional office in Gurgaon costs upwards of ₹2,500 to ₹4,500 per square foot for fit-outs, HVAC installation, IT networking, and electrical cabling. With Yoffices Managed Cabins, companies eliminate upfront CapEx entirely, converting it into predictable monthly operational expenditure.

### 2. Turnkey Enterprise Infrastructure
At Yoffices Sector 45, every private office is pre-fitted with acoustic sound dampening, redundant 1Gbps fiber lines, dual UPS & DG power backup, biometric access control, and ergonomic furnishings. Your team plugs in and starts working on Day 1.

### 3. Elastic Scalability
When your team expands from 10 to 40 members, you simply adjust your private suite layout within the same building without breaking long-term lock-in covenants or negotiating penalty clauses.`,
    coverImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    author: 'Yoffices Research Team',
    category: 'Market Trends',
    tags: ['Gurgaon', 'Private Offices', 'Commercial Real Estate', 'CapEx Optimization'],
    readTime: '6 min read',
    published: true,
    publishedAt: '2026-08-01T10:00:00Z',
    seoTitle: 'Why Gurgaon Companies Prefer Managed Offices in 2026 | Yoffices',
    seoDescription: 'Discover why Gurgaon businesses choose turnkey private offices over traditional commercial leases to save CapEx and scale faster.',
  },
  {
    id: 'blog-gst-virtual-office-haryana',
    title: 'Complete Guide to Haryana GST & ROC Registration with a Virtual Office in Gurgaon',
    slug: 'complete-guide-haryana-gst-roc-virtual-office-gurgaon',
    excerpt: 'Everything founders and corporate finance teams need to know regarding statutory compliance, NOCs, utility bills, and physical verification.',
    content: `Setting up a corporate presence in Haryana without incurring physical office overheads is now straightforward through compliant virtual office solutions.

### Key Documents Provided by Yoffices:
1. **Notarized Commercial Rent Agreement** with clear property description.
2. **Latest Paid Commercial Electricity Bill** confirming active utility supply.
3. **No Objection Certificate (NOC)** directly from the legal property owner.
4. **Signage Display & Physical Desk Space** for government tax officer inspections.

Whether expanding your e-commerce operations into Haryana for state-specific GSTIN fulfillment or registering a new private limited company, Yoffices Sector 32 & 45 provides 100% compliant documentation.`,
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    author: 'Compliance & Legal Desk',
    category: 'Regulatory & GST',
    tags: ['Virtual Office', 'Haryana GST', 'ROC Registration', 'Gurgaon Business'],
    readTime: '5 min read',
    published: true,
    publishedAt: '2026-08-10T12:00:00Z',
    seoTitle: 'Haryana GST Virtual Office in Gurgaon | Complete Guide | Yoffices',
    seoDescription: 'How to obtain Haryana GST registration and MCA compliance using a certified virtual office in Sector 32 & 45 Gurgaon.',
  },
];

export const INITIAL_TESTIMONIALS: TestimonialData[] = [
  {
    id: 'test-1',
    name: 'Vikram Malhotra',
    role: 'Co-Founder & CTO',
    company: 'FinApex Technologies',
    content: 'Moving our 24-member engineering team into Yoffices Sector 45 was the best operational decision we made. The fiber internet reliability, acoustic soundproofing in the cabins, and responsive facility staff are top notch.',
    rating: 5,
    workspaceType: 'Private Office',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    featured: true,
    published: true,
  },
  {
    id: 'test-2',
    name: 'Ananya Singhania',
    role: 'Director of Operations',
    company: 'Aura Logistics India',
    content: 'The Haryana GST registration process using Yoffices Sector 32 virtual office took less than 4 days. All NOCs, utility bills, and signage inspections went through smoothly without a single objection.',
    rating: 5,
    workspaceType: 'Virtual Office',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    featured: true,
    published: true,
  },
  {
    id: 'test-3',
    name: 'Rohit Aggarwal',
    role: 'Commercial Asset Investor',
    company: 'Aggarwal Capital Partners',
    content: 'The franchise workstation model provides transparent monthly disbursements right on the first of every month. The security cheques and professional legal documentation give total peace of mind.',
    rating: 5,
    workspaceType: 'Franchise Partner',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    featured: true,
    published: true,
  },
];

export const INITIAL_FAQS: FAQData[] = [
  {
    id: 'faq-1',
    category: 'Workspaces',
    question: 'What is included in the monthly rent for a Private Office at Yoffices?',
    answer: 'The monthly fee is 100% all-inclusive: fully furnished ergonomic seating, dedicated lockable cabins, high-speed 1Gbps internet, 100% DG power backup, electricity, air conditioning, daily housekeeping, complimentary conference room hours, and unlimited gourmet coffee/tea.',
    order: 1,
    published: true,
  },
  {
    id: 'faq-2',
    category: 'Workspaces',
    question: 'Where are Yoffices centers located in Gurugram?',
    answer: 'Our primary operational workspace and co-living center is located at Plot No. 863, Sector 45, Gurugram (minutes from Millennium City Centre Metro). Our corporate compliance and regulatory headquarters is situated in Sector 32 Institutional Area, Gurugram.',
    order: 2,
    published: true,
  },
  {
    id: 'faq-3',
    category: 'Virtual Office',
    question: 'Will I get all required documents for Haryana GST and ROC registration?',
    answer: 'Yes. We provide a notarized Rent Agreement, latest paid electricity bill, owner NOC, and physical signage verification required by GST and MCA authorities.',
    order: 3,
    published: true,
  },
  {
    id: 'faq-4',
    category: 'Franchise',
    question: 'How do the 3 post-dated security cheques work in the franchise model?',
    answer: 'Upon signing the 3-year agreement, Yoffices issues 3 post-dated annual security cheques to the partner upfront. As monthly rental disbursements are completed across each operational year, the partner returns that corresponding year’s security cheque.',
    order: 4,
    published: true,
  },
  {
    id: 'faq-5',
    category: 'Work + Stay',
    question: 'How does the Work + Stay dormitory accommodation work?',
    answer: 'Our Work + Stay program provides integrated luxury co-living dormitories and executive suites with attached premium dedicated desks, high-speed fiber internet, and 24/7 building security in Sector 45 Gurgaon.',
    order: 5,
    published: true,
  },
];
